### ISSUE TITLE
缺少台湾省的数据

### ISSUE THREAD

**Issue by lison16** [dwqs/area-data#2]
缺少台湾省的数据

**Comment by dwqs** [comment]
从 [官方数据] (http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201703/t20170310_1471429.html)看，港澳台没有太多信息

**Comment by lison16** [comment]
这个暂时没办法，因为国家统计局官网也没找到数据

**Comment by dwqs** [comment]
嗯
