### ISSUE TITLE
data不能正常加载

### ISSUE THREAD

**Issue by bitmoonz** [dwqs/area-data#7]
![image](https://user-images.githubusercontent.com/12149022/40176930-9409f064-5a0f-11e8-8348-5891a4ea215f.png)
![image](https://user-images.githubusercontent.com/12149022/40177115-30de5fec-5a10-11e8-91e9-825eae6c3f1f.png)

` <area-cascader :level='0' :data='pca' type='text' v-model="selected"></area-cascader>`

你好，请问data不能正常加载是为什么

**Comment by dwqs** [comment]
![image](https://user-images.githubusercontent.com/7871813/40178465-1b84fda0-5a14-11e8-8cc4-ec640df43cb0.png)
 
你这没提供地区数据吧

**Comment by bitmoonz** [comment]
提供了的 
![image](https://user-images.githubusercontent.com/12149022/40213774-d44cf250-5a89-11e8-9290-2fd116dabef0.png)

![image](https://user-images.githubusercontent.com/12149022/40213765-c51f3f4a-5a89-11e8-8b7c-5b5f105ffaac.png)

**Comment by dwqs** [comment]
能看下 `target.vue` 文件的更多代码吗

**Comment by bitmoonz** [comment]
![image](https://user-images.githubusercontent.com/12149022/40214031-2f9d9b4a-5a8b-11e8-97e4-3659240349fc.png)
![image](https://user-images.githubusercontent.com/12149022/40214054-42216ae4-5a8b-11e8-8fb1-ea3de8e015d9.png)

**Comment by dwqs** [comment]
@bitmoonz 看我上面补充的回复

**Comment by bitmoonz** [comment]
好了耶，谢谢！
